### ISSUE TITLE
Can't control emulator while capslock is enabled.

### ISSUE THREAD

**Issue by UnRedKnown** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#108] opened 2024-07-08 15:44 UTC
When capslock is enabled, it is impossible to control the virtual Thumby in the emulator using WASD

**Comment by ace-dent** [comment] 2024-07-08 16:47
Confirmed - and already noted. Duplicate of #19.

**Closed** 2024-12-09 13:09 UTC
