### ISSUE TITLE
Latest update has broken emulation

### ISSUE THREAD

**Issue by Connor-McCloskey** [TinyCircuits/TinyCircuits-Thumby-Code-Editor#88] opened 2023-03-10 22:11 UTC
It appears that the recent changes have broken the emulator. Attempting to start the emulator results in nothing happening.  I have tried using both the "start" button and the added hotkey (ctrl+q).

**Comment by masonova1** [comment] 2023-03-10 22:16
This issue is caused by page caching on some browsers. From @jmtinycircuits in the Discord:
`I would try doing F12 -> Network -> Disable cache, refreshing the page with the F12 panel still open, then try hard resetting the page.`
Go ahead and comment to reopen if the issue persists. In the meantime, I'm gonna close this here.

**Closed by masonova1** 2023-03-10 22:16 UTC
